apiVersion: apps/v1
kind: Deployment
metadata:
  name: two-tier-flask-mysql-app-deploy
  labels:
    app: two-tier-flask-mysql-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: two-tier-flask-mysql-app
  template:
    metadata:
      labels:
        app: two-tier-flask-mysql-app
    spec:
      containers:
        - name: two-tier-flask-mysql-app
          image: robinthakur00/flaskapp:latest
          env:
            - name: MYSQL_HOST
              value: "10.98.19.211"          # this is your mysql's service clusture IP, Make sure to change it with yours
            - name: MYSQL_PASSWORD
              value: "admin"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_DB
              value: "mydb"
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
